swiftmailer:
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:  smtp
    host:       smtp.gmail.com
    username:   pavophilip@gmail.com
    password:   my1alm3der
    auth_mode:         login
    port:              587
    encryption:        tls
